### ISSUE TITLE
"ReadableStream uploading is not supported" on POST requests in Safari

### ISSUE THREAD

**Issue by valkanov** [vmware/transport-typescript#36]
Safari Version 14.0.1 (15610.2.11.51.10, 15610)
`transport` version: 1.2.4
POST requests fails in Safari with "ReadableStream uploading is not supported".
`new Request` wraps the request body in `ReadableStream`, which is not supported by Safari.
The request fails when evaluated -  to reproduce it console.log the request before passing it to `fetch` or evaluate it in the developer console using a breakpoint (https://bugs.webkit.org/show_bug.cgi?id=203617).
Also wrong `fetch` instance could be used by `transport` if `fetch` is available by a 3rd party library.

**Comment by jooskim** [comment]
Hey @valkanov thanks for the bug report! It seems that you’re already working on the fix. I’ll shortly review your PR tomorrow and get back to you.
